### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.general'

### ISSUE THREAD

**Issue by pk-1196** [moured/YOLO-ONNX-Parse-Example#2]
@moured  hii i am putting the ipynb fle in yolov5 folder and running it but giving following error . How to resolve it ?

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9ea6b51bf652> in <module>
      3 import numpy as np
      4 import torch
----> 5 from utils.general import non_max_suppression
      6 import cv2 # to drow rectangles boxes on the image
      7 import matplotlib.pyplot as plt # to plot the image

ModuleNotFoundError: No module named 'utils.general'

**Comment by moured** [comment]
@pk-1196  hi, please make sure that YOLO_ONNX_inference.ipynb is in the yolov5/ folder because utils. =general is looking for utils folder. Otherwise, use sys to add the path  " sys.path.append('PATH_OF_YOLOV5')

good luck

**Comment by pk-1196** [comment]
@moured  Hi i have kept in same file but the error is as below , any idea how to resolve this .
Thanks

ImportError                               Traceback (most recent call last)
<ipython-input-2-9ea6b51bf652> in <module>
      3 import numpy as np
      4 import torch
----> 5 from utils.general import non_max_suppression
      6 import cv2 # to drow rectangles boxes on the image
      7 import matplotlib.pyplot as plt # to plot the image

~\thinking_stack\onnx\YOLOv5-master\utils\general.py in <module>
     23 
     24 from utils.google_utils import gsutil_getsize
---> 25 from utils.metrics import fitness
     26 from utils.torch_utils import init_torch_seeds
     27 

~\thinking_stack\onnx\YOLOv5-master\utils\metrics.py in <module>
      3 from pathlib import Path
      4 
----> 5 import matplotlib.pyplot as plt
      6 import numpy as np
      7 import torch

~\anaconda3\lib\site-packages\matplotlib\__init__.py in <module>
    105 # cbook must import matplotlib only within function
    106 # definitions, so it is safe to import from it here.
--> 107 from . import _api, cbook, docstring, rcsetup
    108 from matplotlib.cbook import MatplotlibDeprecationWarning, sanitize_sequence
    109 from matplotlib.cbook import mplDeprecation  # deprecated

ImportError: cannot import name '_api' from partially initialized module 'matplotlib' (most likely due to a circular import) (C:\Users\prave\anaconda3\lib\site-packages\matplotlib\__init__.py)
