### ISSUE TITLE
how to input two images stacked together 

### ISSUE THREAD

**Issue by pk-1196** [moured/YOLO-ONNX-Parse-Example#3]
Right now our input size is (1,3,640,640)
how to stack two images so that images input size will be (2,3,640,640) 

for input size(2,3,640,640) we need to export onnx model by making batch --2 .
Need help in stacking 2 images what to make changes in the code .
Thanks

**Comment by moured** [comment]
hello @pk-1196 I will review this today & tomorrow wait for a response, Thank you.

**Comment by pk-1196** [comment]
hii i have figured out the way to stack the images 
##Load onnx model
import time
###start = time.time()
session = onnxruntime.InferenceSession(model_path)

print("The model expects input shape: ", session.get_inputs()[0].shape)
batch_size = session.get_inputs()[0].shape[0]
img_size_h = session.get_inputs()[0].shape[2]
img_size_w = session.get_inputs()[0].shape[3]


def size(im1):
    im1 = Image.open(im1)
    im1 = im1.resize((img_size_w, img_size_h))
    im1 = np.transpose(im1, (2, 0, 1)).astype(np.float32)
    im1 = np.expand_dims(im1, axis=0)
    im1 /= 255.0 # Normalize all pixels
    ##print('im1',im1)
    return im1
img1 = size(im1)
img2 = size(im2)

out = np.concatenate([img1,img2], axis=0)
print(out.shape)

###Feedforward the Image 
input_name = session.get_inputs()[0].name
start = time.time()

outputs = session.run(None, {input_name: out})
print(time.time() - start)


using above piece of code we can stack the images , for this we have to export the yolo model to onnx by keeping batch size of 2 .

This is one way to stack the images which i got but other way may be . But still i am struggling to get prediction output batch wise which i am passing .
Suppose i have passed the batch of 4 images together then want output of whole batch but unable to get that please do help Thanks

**Comment by moured** [comment]
Thanks for your contribution

**Comment by pk-1196** [comment]
@moured 
Can u check how to get the output batch-wise suppose above i have stacked two images so the output i should get for batch of 2 images .....can u suggest me the changes to be done unable to figure it out till now. Hope you understand my problem else i will try to explain more thanks for your response .

**Comment by moured** [comment]
@pk-1196  It would be appreciated if you can give more details. What is the output shape you have now? maybe you can share your notebook or code ZIP or google colab

**Comment by pk-1196** [comment]
input shape is (2,3,640,640) and output shape is also (2,3,640,640) 
One thing which i have observed that on onnx model accuracy is decreasing i.e. wrong bounding box is predicted .

Can you give any example on stacking 2,3 images together and have predicting the output batchwise . May be i am dong wrong .
